### ISSUE TITLE
Redundant Files

### ISSUE THREAD

**Issue by Treslex** [rzen1th/ArcCW_UD#2]
I did a quick search and found that the following files are currently redundant.

By redundant I mean that they are not referenced by any other file or used anywhere. This includes .vmt s which aren't referenced in .mdl s.

The tool I made to generate this list is currently unable to sort mismatching references so some items in this list could possibly be used somewhere if the .ToLowers() of the files are not exactly the same.

...\materials\entities\arccw_ud_870.png
...\materials\entities\arccw_ud_glock.png
...\materials\entities\arccw_ud_m1014.png
...\materials\entities\arccw_ud_m16.png
...\materials\entities\arccw_ud_mini14.png
...\materials\entities\arccw_ud_uzi.png
...\materials\arccw\weaponicons\arccw_ud_870.vmt
...\materials\arccw\weaponicons\arccw_ud_870.vtf
...\materials\arccw\weaponicons\arccw_ud_glock.vmt
...\materials\arccw\weaponicons\arccw_ud_glock.vtf
...\materials\arccw\weaponicons\arccw_ud_m1014.vmt
...\materials\arccw\weaponicons\arccw_ud_m1014.vtf
...\materials\arccw\weaponicons\arccw_ud_m16.vmt
...\materials\arccw\weaponicons\arccw_ud_m16.vtf
...\materials\arccw\weaponicons\arccw_ud_mini14.vmt
...\materials\arccw\weaponicons\arccw_ud_mini14.vtf
...\materials\arccw\weaponicons\arccw_ud_uzi.vmt
...\materials\arccw\weaponicons\arccw_ud_uzi.vtf
...\materials\entities\att\arccw_ud_tp_this_perk_is_fucking_useless.png
...\models\weapons\arccw\atts\mini_100_lhik.mdl
...\models\weapons\arccw\atts\sd_lhik.mdl
...\models\weapons\arccw\atts\stub_100_lhik.mdl
...\models\weapons\arccw\ud_shells\338.mdl
...\models\weapons\arccw\ud_shells\762.mdl
...\materials\models\weapons\arccw\temp\cmag_d.jpg
...\materials\models\weapons\arccw\temp\shotgun_spas_ud.jpg
...\materials\models\weapons\arccw\temp\someones gotta convert these into vtfs and replace the old ones.txt
...\materials\models\weapons\arccw\ud_870\870_color.vtf
...\materials\models\weapons\arccw\ud_870\870_normal.vtf
...\materials\models\weapons\arccw\ud_870\shotgun_black.vmt
...\materials\models\weapons\arccw\ud_870\shotgun_color.vtf
...\materials\models\weapons\arccw\ud_870\shotgun_normal.vtf
...\materials\models\weapons\arccw\ud_870\shotgun_polymer_color.vtf
...\materials\models\weapons\arccw\ud_870\shotgun_polymer_normal.vtf
...\materials\models\weapons\arccw\ud_glock\attachments_diffuse.vtf
...\materials\models\weapons\arccw\ud_glock\attachments_normals.vtf
...\materials\models\weapons\arccw\ud_glock\bigstick.vmt
...\materials\models\weapons\arccw\ud_glock\glock.vtf
...\materials\models\weapons\arccw\ud_glock\glock_autoswitch.vtf
...\materials\models\weapons\arccw\ud_glock\glock_autoswitch_normal.vtf
...\materials\models\weapons\arccw\ud_glock\glock_normals.vtf
...\materials\models\weapons\arccw\ud_glock\glock_tan.vtf
...\materials\models\weapons\arccw\ud_glock\pist_glock18.vmt
...\materials\models\weapons\arccw\ud_glock\pist_glock18_dark.vmt
...\materials\models\weapons\arccw\ud_m1014\benelli.vtf
...\materials\models\weapons\arccw\ud_m1014\benelli_n.vtf
...\materials\models\weapons\arccw\ud_m1014\m1014_col.vtf
...\materials\models\weapons\arccw\ud_m1014\m1014_n.vtf
...\materials\models\weapons\arccw\ud_m1014\salvo12.vmt
...\materials\models\weapons\arccw\ud_m1014\salvo12.vtf
...\materials\models\weapons\arccw\ud_m1014\salvo12_exp.vtf
...\materials\models\weapons\arccw\ud_m1014\shell.vtf
...\materials\models\weapons\arccw\ud_m1014\shell_n.vtf
...\materials\models\weapons\arccw\ud_m16\m16a2_exp_new.vtf
...\materials\models\weapons\arccw\ud_m16\m16a2_new.vtf
...\materials\models\weapons\arccw\ud_m16\m16a2_normal_new.vtf
...\materials\models\weapons\arccw\ud_m16\m16_color.jpg
...\materials\models\weapons\arccw\ud_m16\m16_normal.jpg
...\materials\models\weapons\arccw\ud_m16\m16_spec.jpg
...\materials\models\weapons\arccw\ud_shells\12gauge_shell_bump.vtf
...\materials\models\weapons\arccw\ud_shells\338mag_shell_bump.vtf
...\materials\models\weapons\arccw\ud_shells\556mm_shell_bump.vtf
...\materials\models\weapons\arccw\ud_shells\57mm_shell_bump.vtf
...\materials\models\weapons\arccw\ud_shells\762nato_shell_bump.vtf
...\materials\models\weapons\arccw\ud_shells\9mm_shell_bump.vtf
...\materials\models\weapons\arccw\ud_uzi\flashlight_color.vtf
...\materials\models\weapons\arccw\ud_uzi\flashlight_normals.vtf
...\materials\models\weapons\arccw\ud_uzi\uzi.vmt
...\materials\models\weapons\arccw\ud_uzi\uzi.vtf
...\materials\models\weapons\arccw\ud_uzi\uzi_attachment.vtf
...\materials\models\weapons\arccw\ud_uzi\uzi_attachment_normal.vtf
...\materials\models\weapons\arccw\ud_uzi\uzi_color.vtf
...\materials\models\weapons\arccw\ud_uzi\uzi_normal.vtf
...\materials\models\weapons\arccw\ud_uzi\uzi_pubg.vtf
...\materials\models\weapons\arccw\ud_uzi\uzi_pubg_n.vtf
...\materials\models\weapons\arccw\ud_uzi\uzi_stock_color.vtf
...\materials\models\weapons\arccw\ud_uzi\uzi_stock_normal.vtf
...\materials\models\weapons\arccw\ud_uzi\uzi_stock_polymer.vtf
...\materials\models\weapons\arccw\ud_uzi\uzi_stock_polymer_n.vtf
...\materials\models\weapons\arccw\ud_uzi\uzi_stock_wood.vtf
...\materials\models\weapons\arccw\ud_uzi\uzi_stock_wood_n.vtf
...\sound\weapons\arccw_ud\glock\fire_data\e08\d08\e0808111.au
...\sound\weapons\arccw_ud\glock\fire_data\e08\d08\e0808191.au
...\sound\weapons\arccw_ud\glock\fire_data\e08\d08\e08081ac.au
...\sound\weapons\arccw_ud\glock\fire_data\e08\d08\e08081e5.au
...\sound\weapons\arccw_ud\glock\fire_data\e08\d08\e08081f1.au
...\sound\weapons\arccw_ud\glock\fire_data\e08\d08\e08082a3.au
...\sound\weapons\arccw_ud\glock\fire_data\e08\d08\e0808332.au
...\sound\weapons\arccw_ud\glock\fire_data\e08\d08\e080833e.au
...\sound\weapons\arccw_ud\glock\fire_data\e08\d08\e0808496.au
...\sound\weapons\arccw_ud\glock\fire_data\e08\d08\e080855a.au
...\sound\weapons\arccw_ud\glock\fire_data\e08\d08\e080864f.au
...\sound\weapons\arccw_ud\glock\fire_data\e08\d08\e08086d6.au
...\sound\weapons\arccw_ud\glock\fire_data\e08\d08\e0808765.au
...\sound\weapons\arccw_ud\glock\fire_data\e08\d08\e08088b6.au
...\sound\weapons\arccw_ud\glock\fire_data\e08\d08\e08088ce.au
...\sound\weapons\arccw_ud\glock\fire_data\e08\d08\e0808986.au
...\sound\weapons\arccw_ud\glock\fire_data\e08\d08\e0808c2a.au
...\sound\weapons\arccw_ud\glock\fire_data\e08\d08\e0808c9c.au
...\sound\weapons\arccw_ud\glock\fire_data\e08\d08\e0808cfd.au
...\sound\weapons\arccw_ud\glock\fire_data\e08\d08\e0808d0d.au
...\sound\weapons\arccw_ud\glock\fire_data\e08\d08\e0808d8e.au
...\sound\weapons\arccw_ud\glock\fire_data\e08\d08\e0808e08.au

**Comment by Treslex** [comment]
> I did a quick search and found that the following files are currently redundant.
> 
> By redundant I mean that they are not referenced by any other file or used anywhere. This includes .vmt s which aren't referenced in .mdl s.
> 
> The tool I made to generate this list is currently unable to sort mismatching references so some items in this list could possibly be used somewhere if the .ToLowers() of the files are not exactly the same.
> 
> Redundant Files

Only reason for posting this is so that they can be removed if they are unnecessarily taking up space.

**Comment by TheOnly8Z** [comment]
most files are not actually redundant, they just use string concat for readability.
